{{- define "kafka-cruise-control" -}}
{{- $cruise_control := . -}}
---
{{ range .Values.cruise_control_list }}
{{- $container_name := printf "kafka-cruise-control_%s_%s" .config.application_name .config.environment | lower |replace "_" "-"| replace "*" "all" |replace "." "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $container_name }}
  namespace: {{ $cruise_control.Values.namespace }}
  labels:
    app.kubernetes.io/name: "kafka-cruise-control"
spec:
  {{- if $cruise_control.Values.strategy }}
  strategy:
    type: Recreate
  {{ end }}
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: '{{ $container_name | replace "_" "-" }}'
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ $container_name | replace "_" "-" }}'
        team: {{ $cruise_control.Values.team }}
    spec:
      containers:
        - name: {{ $cruise_control.Values.application }}
          image: "{{ $cruise_control.Values.image.repository }}:{{ $cruise_control.Values.image.tag }}"
          imagePullPolicy: {{ $cruise_control.Values.image.pullPolicy }}
          ports:
            - name: {{ .config.application_name }}
              containerPort: 8090
              protocol: TCP
          resources:
            limits:
              cpu: "{{ .cpu_limit }}m"
              memory: "{{ .memory_limit }}Mi"
            requests:
              cpu: "1m"
              memory: "1Mi"
          volumeMounts:
            - name: config-{{ $container_name }}
              mountPath: /opt/cruise-control/config/cruisecontrol.properties
              subPath: cruisecontrol.properties
            - name: capacity-{{ $container_name }}
              mountPath: /opt/cruise-control/capacity             
      volumes:
        - name: config-{{ $container_name }}
          configMap:
            name: config-{{ $container_name }}
            items:
             - key: cruisecontrol.properties
               path: cruisecontrol.properties
        - name: capacity-{{ $container_name }}
          configMap:
            name: config-{{ $container_name }}
            items:
             - key: capacity.json 
               path: capacity.json               
      {{- with $cruise_control.Values.cruise_control_nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $cruise_control.Values.cruise_control_affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $cruise_control.Values.cruise_control_tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
{{- end }}
{{- end }}
