{{- define "kafka-cruise-control-ingress" -}}
{{- $cruise_control := . -}}
---
{{ range .Values.cruise_control_list }}
{{- $container_name := printf "kafka-cruise-control_%s_%s" .config.application_name .config.environment | lower |replace "_" "-"| replace "*" "all" |replace "." "-" }}
{{- $host_name := printf "kafka-cruise-control-%s.%s-%s.service" .config.application_name .config.environment .config.dc }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- if $.Values.ingress.annotations }}
  annotations:
{{ toYaml $.Values.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ .config.application_name }}
  namespace: {{ $cruise_control.Values.namespace }}
spec:
  ingressClassName: {{ $cruise_control.Values.ingress.ingressClassName }}
  rules:
  - host: {{ $host_name  }}
    http:
      paths:
        - backend:
            service:
              name: {{ .config.application_name }}
              port: 
                name: {{ .config.application_name }}
          path: /
          pathType: ImplementationSpecific
---
{{- end }}
{{- end }}

